### ISSUE TITLE
Which Cybersource method is it implementing?

### ISSUE THREAD

**Issue by chrisvidal** [PatronBase/omnipay-cybersource-hosted#1]
Is this implementing the `Cybersource Secure Acceptance Hosted Checkout` method?
thanks

**Comment by leith** [comment]
Yes, that's correct! It's noted in the [README.MD](https://github.com/PatronBase/omnipay-cybersource-hosted/blob/master/README.md) as well, particularly since they changed the name a while back.

**Comment by chrisvidal** [comment]
ok thanks. Just realized that this is for Omnipay v2. Did you by any chance update it to match OmniPay v3?

**Comment by leith** [comment]
@chrisvidal sorry I missed this message for some reason - v3 support was added a few weeks after your message though, so hopefully you picked up on that!
